### ISSUE TITLE
make some callbacks per-request

### ISSUE THREAD

**Issue by vickenty** [gonzus/http-nghttp2#5]
- `on_header`
- `on_data_chunk_recv`
- `on_stream_close`

**Comment by gonzus** [comment]
@vickenty , at this point I'm not sure I remember anymore what this issue was about... Can you expand a bit?

**Comment by vickenty** [comment]
The idea was to let users specify these callbacks separately for each submitted request, to let users handle data from different streams using different callbacks. When the issue was created, we only supported one callback of each type per session.

**Comment by xsawyerx** [comment]
Oh, cool. So now we support all of those callbacks, and we have three levels of callbacks: Low-level library, high-level library, and user callbacks. The user callbacks are called from the high-level library.

So, all in all, I think we've resolved this.
