### ISSUE TITLE
Move on_stream_close processing from NGHTTP2::Client to the caller

### ISSUE THREAD

**Issue by gonzus** [gonzus/http-nghttp2#6]
Right now NGHTTP2::Client accumulates all data chunks received into a hash keyed by stream_id, and passes the full result back to a caller using on_done. This seems too specific for the generic client, and should probably be done in the caller.

**Comment by xsawyerx** [comment]
I'm not sure. I think this is one of the key requirements for any HTTP client. This could arguably be done in whatever user agent is written on top of it, but this optional ability allows one to use these bindings without waiting for a user agent and having its overhead.

**Comment by gonzus** [comment]
Maybe the caller could pass in a "handler" object, so that inside on_data_chunk, the library calls this object with each chunk. Then depending on the type of object you pass, you achieve different results.

Anyway, the other point of this issue is to make sure we do this with the proper callback (on_frame_recv? on_stream_close?). Perhaps this is OK already, need to check.

**Comment by xsawyerx** [comment]
Isn't there already a chunk callback? When a user provides that, their code is called every time we get a new chunk.

The benefit of only doing this using `on_done` is so we don't aggregate on every `on_stream_close`. If a user does not provide `on_done`, we just don't aggregate and save on memory.

One could argue that this is so essential that we might as well do it all the time and expose it on `on_stream_close`. (We can also not do it unless a user gave `on_stream_close`.)

Does that make sense? I would be in favor of that.

**Comment by gonzus** [comment]
So, if I understand your point:
- The user can already provide their own on_data_chunk_recv callback.
- If the user provides an on_done, we accumulate the data per stream and pass it back to the user when on_stream_close is triggered; if they do not provide it, we don't accumulate.

Now I believe you are right, this should suffice. If you agree, I will close this issue.

**Comment by xsawyerx** [comment]
Hmm... it's correct, except for the point that it's provided on the `on_stream_close`. It isn't. Let me rewrite that part:

* You can currently use `on_data_chunk_recv` for every data chunk. You can aggregate them if you want, based on the stream ID.
* You can also provide `on_stream_close` which is called when the stream closes at the end of a request.
* If you want us to aggregate based on stream ID for you, you can use `on_done`, which is effectively run when the `on_stream_close` is run but gives you all the content.

Another way to see it:

* `on_data_chunk_recv` gives you each chunk. Do with it as you wish.
* `on_stream_close` tells you when we're done.
* `on_done` gives you a form of `on_stream_close` that also has the content of everything in it.

Each of them are independent and you can use them in any formation. None force the usage of others.

**Comment by gonzus** [comment]
I think we both said the same...??? In any case, I already closed the issue, I think we are in agreement.
